// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

/*//////////////////////////////////////////////////////////////////////////////

                    A C C O U N T I N G   &   R O U N D I N G
                          deep stateful fuzz / invariants

  Scope. The custody suite (test/attack/*) proves nobody can point a payout at an address they
  chose. This file proves the complementary thing: that the NUMBERS add up. Value conservation
  across long random sequences of open / withdraw / rebalance / swap, and the rounding direction
  of every leg.

  ------------------------------------------------------------------------------------------------
  HOW "RECOVERABLE VALUE" IS MEASURED — this is the load-bearing methodological choice.

  Every valuation in this file is done by ACTUALLY EXITING. `_valueAll()` takes a state snapshot,
  walks every live position, calls the real owner-only `withdraw()` for its full stored liquidity,
  measures what each owner's wallet actually received, and then rolls the chain back. Nothing here
  re-derives Uniswap's math and nothing here models MolePositions. The number asserted on is the
  number a user would really get if they exited in that block.

  That matters because the 2026-08-01 exploit was invisible to `p.liquidity`: stored liquidity
  agreed with the PoolManager in UNITS at every single point while 98.8% of a deposit walked out
  of the position. Any invariant written over the liquidity integer would have passed. Only an
  invariant written over recoverable TOKENS catches it.

  ------------------------------------------------------------------------------------------------
  THE DUST BOUND, stated and derived. An unbounded tolerance is not a test.

  Uniswap v4 rounds against the liquidity provider on every leg, by construction:

      * mint  (`liquidityDelta > 0`): required amounts are computed with roundUp = TRUE, so the
              payer is charged at most 1 wei per token MORE than the exact real-number amount.
      * burn  (`liquidityDelta < 0`): returned amounts are computed with roundUp = FALSE, so the
              receiver is paid at most 1 wei per token LESS than exact.

  So each liquidity leg can move at most 1 wei per token away from perfect conservation, always in
  the pool's favour. Two constants follow, and every tolerance in this file is built from them:

      DUST_PER_LEG       = 2 wei / token / liquidity leg   (1 wei of v4 rounding + 1 wei of slack)
      DUST_PER_VALUATION = 1 wei / token / live position   (`_valueAll` exits, so it eats the burn
                                                            truncation once per position)

  Leg counts per user action: open = 1, withdraw = 1, rebalance = 2 (burn + mint).

  The stateful test accumulates a budget from the actions it actually performed rather than
  asserting a magic number, so the tolerance is a FUNCTION OF THE TRACE and cannot silently absorb
  a real leak. Concretely: a 48-step trace budgets roughly 200 wei per token against deposits in
  the 1e18..1e22 range — a relative tolerance around 1e-19. The pre-fix bug moved 2.5e19 wei. It is
  not close.

  NOTE ON WHY THE BOUND IS ABSOLUTE AND NOT A PERCENTAGE: the bug this file exists to catch
  destroyed 98.8% of a deposit. Any tolerance expressed as a fraction of principal that was loose
  enough to absorb v4's rounding would also have been loose enough to hide a 1%-per-rebalance
  drip, which over the keeper's rate limit is the same theft on a slower clock.

  ------------------------------------------------------------------------------------------------
  WHAT EACH TEST PINS

  1. testFuzz_stateful_valueIsConservedAcrossLongRandomSequences
     48 random steps over 3 users, asserting after EVERY step:

         Σ recoverable(live positions)  ==  (tokens users paid in − tokens users got back)
                                             + (value change attributable to SWAP steps)

     The right-hand side is measured, not modelled: the user term comes from real wallet balances,
     and the swap term is the change in Σ recoverable observed across steps in which MolePositions
     is not called at all. So open / withdraw / rebalance are required to explain their value
     movement EXACTLY, and a rebalance in particular is required to move zero. That is precisely
     what the old `_settleNet` violated: it moved value on a rebalance step with no user leg to
     explain it.

  2. testFuzz_rebalanceConservesTokenValue — 50k runs. Value immediately before a rebalance equals
     value immediately after, plus the dust the rebalance paid to the owner. The exact property
     whose absence was the exploit.

  3. test_feesCompoundIntoTheOwnerPositionRatherThanLeaking — fees generated by real swaps, then a
     rebalance to the SAME range: liquidity must strictly increase and the contract must still hold
     zero.

  4. testFuzz_openWithdrawRoundTripNeverPaysOutMoreThanItTookIn — log-uniform over the whole
     uint128 liquidity range (1 wei .. 2**128-1). Rounding must never favour the user.

  5. testFuzz_identicalRangeNeighbourIsUnaffectedByAFullExit — two positions at byte-identical tick
     ranges; one exits completely; the other's recorded liquidity, on-chain liquidity AND
     recoverable tokens must be unchanged to the wei.

  ------------------------------------------------------------------------------------------------
  KEEPING THE SUITE HONEST. Three supporting tests exist purely so the five above cannot rot into
  green noise:

     test_negativeControl_theConservationCheckDetectsALeak
         Injects a leak of the same SHAPE as the 2026-08-01 bug and asserts the conservation
         equality breaks by exactly the leaked amount. A conservation test never observed to fail
         is indistinguishable from assertTrue(true).

     test_rebalanceCorpusIsNotVacuous / test_roundTripCorpusIsNotVacuous
         Fuzz state resets between runs, so a counter inside a fuzz test can never be read back.
         These replay the identical case bodies over a fixed pseudo-random corpus in a single run
         and assert on the outcome mix, so "most draws bounced off a revert" fails loudly instead
         of passing quietly.

  ------------------------------------------------------------------------------------------------
  RUNNING

      forge test --match-path 'test/invariant/InvariantAccounting.t.sol'
      FOUNDRY_PROFILE=deep forge test --match-path 'test/invariant/InvariantAccounting.t.sol'

  The stateful test carries `forge-config: default.fuzz.runs = 128`, because one run is a 48-step
  trace that snapshot-exits every live position at every step — ~19M gas and ~200 real v4 liquidity
  operations, roughly 1000x an ordinary fuzz case. It inherits the full 50,000 under `deep`.

//////////////////////////////////////////////////////////////////////////////*/

import {Deployers} from "@uniswap/v4-core/test/utils/Deployers.sol";
import {MockERC20} from "solmate/src/test/utils/mocks/MockERC20.sol";

import {IPoolManager} from "v4-core/interfaces/IPoolManager.sol";
import {IHooks} from "v4-core/interfaces/IHooks.sol";
import {PoolKey} from "v4-core/types/PoolKey.sol";
import {PoolId, PoolIdLibrary} from "v4-core/types/PoolId.sol";
import {Currency} from "v4-core/types/Currency.sol";
import {ModifyLiquidityParams} from "v4-core/types/PoolOperation.sol";
import {StateLibrary} from "v4-core/libraries/StateLibrary.sol";
import {Position as V4Position} from "v4-core/libraries/Position.sol";

import {MolePositions} from "../../src/MolePositions.sol";
import {deployMoleVault, deployMoleVaultOwned, hookProxyArgs, deployMoleHookAnywhere, TEST_UPGRADE_ADMIN} from "../helpers/ProxyDeploy.sol";

contract InvariantAccounting is Deployers {
    using StateLibrary for IPoolManager;
    using PoolIdLibrary for PoolKey;

    /* ------------------------------------------------------------------- fixture */

    MolePositions internal mole;

    address internal constant KEEPER = address(0xdeadbeef01);
    address internal constant ALICE = address(0xA11CE);
    address internal constant BOB = address(0xB0B);
    address internal constant CAROL = address(0xCA401);

    uint32 internal constant MIN_REBAL_INTERVAL = 1 hours;
    int24 internal constant MIN_WIDTH = 60;
    int24 internal constant MAX_WIDTH = 20_000;

    int24 internal constant SPACING = 60;
    uint24 internal constant FEE = 3000;

    /// @dev Users are funded far above anything the tests spend, so a revert is never a funding
    ///      artefact. 1e36 also leaves `maxLiquidityPerTick` as the binding constraint at the top
    ///      of the liquidity range, which is the constraint we actually want to probe.
    uint256 internal constant USER_FUNDING = 1e36;

    PoolId internal poolId;
    MockERC20 internal tok0;
    MockERC20 internal tok1;

    address[3] internal users;
    mapping(address => uint256) internal startBal0;
    mapping(address => uint256) internal startBal1;

    /// @dev Every position id ever opened by the stateful trace, in order.
    uint256[] internal ids;

    /* ---------------------------------------------------------------- dust model */

    /// @notice v4 rounds against the LP by at most 1 wei per token on each liquidity leg (mint
    ///         rounds the charge up, burn rounds the payout down). 2 is that wei plus one wei of
    ///         slack so the bound is a strict cap rather than an exact fit.
    uint256 internal constant DUST_PER_LEG = 2;

    /// @notice `_valueAll()` prices a position by actually burning it, so each valuation eats the
    ///         burn-side truncation once, per token, per live position.
    uint256 internal constant DUST_PER_VALUATION = 1;

    /// @notice Closed-form bound for a single open -> ... -> withdraw round trip on a fixed price:
    ///         1 wei mint round-up + 1 wei per burn leg (up to two legs) + 1 wei of slack.
    uint256 internal constant ROUND_TRIP_DUST = 4;

    /* -------------------------------------------------------------------- setUp */

    function setUp() public {
        deployFreshManagerAndRouters();
        deployMintAndApprove2Currencies();

        (key, poolId) = initPool(currency0, currency1, IHooks(address(0)), FEE, SPACING, SQRT_PRICE_1_1);

        tok0 = MockERC20(Currency.unwrap(currency0));
        tok1 = MockERC20(Currency.unwrap(currency1));

        // Deep background book so our positions are never the whole pool and swaps always execute.
        modifyLiquidityRouter.modifyLiquidity(
            key,
            ModifyLiquidityParams({tickLower: -120_000, tickUpper: 120_000, liquidityDelta: 20_000e18, salt: 0}),
            ZERO_BYTES
        );

        mole = deployMoleVault(manager, KEEPER, MIN_REBAL_INTERVAL, MIN_WIDTH, MAX_WIDTH, address(0), 0, 0, 0, 0, 10_000, 0, 0, address(0));
        mole.whitelistPool(key);

        users[0] = ALICE;
        users[1] = BOB;
        users[2] = CAROL;
        for (uint256 i; i < users.length; ++i) {
            _fund(users[i]);
        }
        _fund(KEEPER);
    }

    function _fund(address who) internal {
        tok0.mint(who, USER_FUNDING);
        tok1.mint(who, USER_FUNDING);
        vm.startPrank(who);
        tok0.approve(address(mole), type(uint256).max);
        tok1.approve(address(mole), type(uint256).max);
        vm.stopPrank();
        startBal0[who] = tok0.balanceOf(who);
        startBal1[who] = tok1.balanceOf(who);
    }

    /* ------------------------------------------------------------------ helpers */

    function _bal(address who) internal view returns (uint256, uint256) {
        return (tok0.balanceOf(who), tok1.balanceOf(who));
    }

    /// @dev The single number `_settleNet` used to accumulate. If it is ever non-zero the shared
    ///      pot is back and every one of the 2026-08-01 findings is live again.
    function _assertNoInventory(string memory where) internal view {
        assertEq(tok0.balanceOf(address(mole)), 0, string.concat("token0 inventory @ ", where));
        assertEq(tok1.balanceOf(address(mole)), 0, string.concat("token1 inventory @ ", where));
    }

    function _currentTick() internal view returns (int24 tick) {
        (, tick,,) = StateLibrary.getSlot0(manager, poolId);
    }

    function _alignedTick() internal view returns (int24) {
        int24 t = _currentTick();
        return (t / SPACING) * SPACING;
    }

    function _onChainLiquidity(uint256 id, int24 lo, int24 hi) internal view returns (uint128) {
        bytes32 posKey = V4Position.calculatePositionKey(address(mole), lo, hi, bytes32(id));
        return manager.getPositionLiquidity(poolId, posKey);
    }

    /// @dev Called through `this.` so it can be wrapped in try/catch. Swaps are performed by the
    ///      TEST contract, never by a tracked user, so they can never pollute the user-flow term.
    function externalSwap(bool zeroForOne, int256 amountSpecified) external {
        require(msg.sender == address(this), "self only");
        swap(key, zeroForOne, amountSpecified, ZERO_BYTES);
    }

    function _churnFees(uint256 amount, uint256 rounds) internal {
        for (uint256 i; i < rounds; ++i) {
            swap(key, true, -int256(amount), ZERO_BYTES);
            swap(key, false, -int256(amount), ZERO_BYTES);
        }
    }

    /* ------------------------------------------------------- EXACT VALUATION */

    /// @notice Recoverable value of ONE position: what its owner would actually receive, right now,
    ///         through the real withdraw path. Measured by doing it inside a state snapshot and
    ///         rolling back. Includes accrued-but-uncollected fees, because a withdraw collects
    ///         100% of them.
    function _valueOne(uint256 id) internal returns (uint256 v0, uint256 v1) {
        uint128 liq = mole.getPosition(id).liquidity;
        if (liq == 0) return (0, 0);
        uint256 snap = vm.snapshotState();
        address o = mole.ownerOf(id);
        (uint256 b0, uint256 b1) = _bal(o);
        vm.prank(o);
        mole.withdraw(id, liq);
        (uint256 a0, uint256 a1) = _bal(o);
        v0 = a0 - b0;
        v1 = a1 - b1;
        require(vm.revertToState(snap), "snapshot rollback failed");
    }

    /// @notice Σ recoverable over every position opened so far.
    /// @dev Exiting position i does not change position j's recoverable amounts: removing liquidity
    ///      moves no price and writes no fee growth, so j's (L, range, feeGrowthInside) are
    ///      untouched. The sum is therefore well defined and order-independent.
    function _valueAll() internal returns (uint256 v0, uint256 v1) {
        uint256 snap = vm.snapshotState();
        for (uint256 i; i < ids.length; ++i) {
            uint256 id = ids[i];
            uint128 liq = mole.getPosition(id).liquidity;
            if (liq == 0) continue;
            address o = mole.ownerOf(id);
            (uint256 b0, uint256 b1) = _bal(o);
            vm.prank(o);
            mole.withdraw(id, liq);
            (uint256 a0, uint256 a1) = _bal(o);
            v0 += a0 - b0;
            v1 += a1 - b1;
        }
        require(vm.revertToState(snap), "snapshot rollback failed");
    }

    function _liveCount() internal view returns (uint256 n) {
        for (uint256 i; i < ids.length; ++i) {
            if (mole.getPosition(ids[i]).liquidity != 0) ++n;
        }
    }

    /// @notice Net tokens users have handed to the system: Σ (start balance − current balance).
    ///         Signed, because fee income can legitimately push a user above their starting balance.
    function _userNet() internal view returns (int256 n0, int256 n1) {
        for (uint256 i; i < users.length; ++i) {
            address u = users[i];
            n0 += int256(startBal0[u]) - int256(tok0.balanceOf(u));
            n1 += int256(startBal1[u]) - int256(tok1.balanceOf(u));
        }
    }

    /// @dev Two's-complement absolute value. Written unchecked so that `type(int256).min` — which
    ///      the fuzzer WILL hand us — yields 2**255 instead of panicking, because a test harness
    ///      that reverts on an input is a test that silently stopped testing.
    function _abs(int256 x) internal pure returns (uint256) {
        unchecked {
            return x >= 0 ? uint256(x) : (~uint256(x) + 1);
        }
    }

    function _rnd(uint256 seed, uint256 step, uint256 tag) internal pure returns (uint256) {
        return uint256(keccak256(abi.encode(seed, step, tag)));
    }

    /* ==========================================================================================
       1.  STATEFUL FUZZ — value conservation across a long random sequence
       ========================================================================================== */

    /// @notice A 48-step random trace over 3 users and 4 action kinds, asserting after EVERY step:
    ///
    ///     Σ recoverable(live positions)  ==  userNet  +  swapAttributed        (± stated dust)
    ///
    ///   userNet         real wallet flow: what users paid in minus what they got back. Includes
    ///                   rebalance dust payouts automatically, since those land in a real wallet.
    ///   swapAttributed  the change in Σ recoverable observed across steps in which MolePositions
    ///                   is never called. Swaps are genuinely allowed to move an LP's token
    ///                   composition and to pay it fees, so this term must exist; it is measured
    ///                   only on pure-swap steps, so it cannot absorb anything MolePositions did.
    ///
    ///   Read the contrapositive: open / withdraw / rebalance must explain their value movement
    ///   through a user wallet, EXACTLY. A rebalance has no user leg, so a rebalance must move
    ///   zero. The pre-fix `_settleNet` moved a rebalance's entire surplus into address(this) with
    ///   no wallet leg at all, which is a violation of this equality on the rebalance step and on
    ///   every step after it.
    ///
    ///   This is the canonical form "- recoverable + paid out == deposited + fees earned", just
    ///   rearranged and with the right-hand term correctly generalised. `userNet` IS
    ///   `deposited − paidOut`, so the equality above is exactly
    ///
    ///       Σ recoverable + paidOut  ==  deposited + swapAttributed.
    ///
    ///   It has to be `swapAttributed` rather than `feesEarned`, and this is not a loosening: an
    ///   LP's token balance changes when the PRICE moves, not only when fees accrue. Asserting
    ///   per-token conservation against fee income alone would be a false statement that could only
    ///   be made true by forbidding swaps — i.e. by deleting the interesting half of the trace.
    ///   Measuring the swap term on steps where MolePositions is never called keeps it honest: it
    ///   is a measurement of the POOL's effect on the positions, taken while the contract under
    ///   test is provably idle, and `_assertStoredLiquidityUnchanged` enforces that idleness.
    ///
    /// DUST: budget accrues per action from DUST_PER_LEG / DUST_PER_VALUATION (see header), so the
    ///       tolerance is a function of the trace. A typical trace budgets ~200 wei per token.
    ///
    /// RUNS: one run is a 48-step trace that snapshot-exits every live position at every step —
    ///       ~19M gas and ~200 real v4 liquidity operations, roughly 1000x an ordinary fuzz case.
    ///       128 on `default` keeps the suite interactive; `deep` takes the full 50,000, which is
    ///       2.4 million individually asserted steps and runs in a couple of minutes.
    /// forge-config: default.fuzz.runs = 128
    /// forge-config: deep.fuzz.runs = 50000
    function testFuzz_stateful_valueIsConservedAcrossLongRandomSequences(uint256 seed) public {
        uint256 STEPS = 48;
        uint256 MAX_POSITIONS = 8;

        int256 swapAtt0;
        int256 swapAtt1;
        uint256 dustBudget; // wei per token, accumulated from the actions actually performed

        uint256 rec0;
        uint256 rec1;

        uint256 nOpen;
        uint256 nWithdraw;
        uint256 nRebalance;
        uint256 nSwap;
        uint256 nRebalanceReverted;

        // Largest |gap| actually observed, logged at the end. This is what makes the dust bound a
        // claim rather than a hope: if the observed maximum sat right under the budget the budget
        // would be doing the work, and the test would be worthless.
        uint256 maxGap;

        for (uint256 step; step < STEPS; ++step) {
            // Time moves so the keeper's per-position rate limit clears at a realistic cadence.
            vm.warp(block.timestamp + 1 + (_rnd(seed, step, 0) % (3 hours)));

            // Steps 0 and 1 are always opens so the trace has something to act on; everything
            // after is weighted-random. No vm.assume anywhere: every draw executes something.
            uint256 kind;
            if (step < 2) {
                kind = 0;
            } else {
                uint256 r = _rnd(seed, step, 1) % 100;
                if (r < 26) kind = 0; // open
                else if (r < 52) kind = 1; // withdraw
                else if (r < 78) kind = 2; // rebalance
                else kind = 3; // swap
            }
            // At the position cap an "open" step becomes a swap step rather than a silent no-op,
            // so the step still does something and `kind` never lies to the failure log.
            if (kind == 0 && ids.length >= MAX_POSITIONS) kind = 3;

            if (kind == 0) {
                address who = users[_rnd(seed, step, 2) % users.length];
                (int24 lo, int24 hi) = _fuzzRange(_rnd(seed, step, 3), _rnd(seed, step, 4));
                uint128 liq = uint128(bound(_rnd(seed, step, 5), 1e12, 1e21));

                vm.prank(who);
                try mole.open(key, lo, hi, liq, type(uint256).max, type(uint256).max, block.timestamp)
                returns (uint256 id) {
                    ids.push(id);
                    ++nOpen;
                    dustBudget += DUST_PER_LEG;
                } catch {}
                (rec0, rec1) = _valueAll();
            } else if (kind == 1) {
                uint256 id = _pickLive(_rnd(seed, step, 6));
                if (id != 0) {
                    uint128 held = mole.getPosition(id).liquidity;
                    uint256 bps = bound(_rnd(seed, step, 7), 1, 10_000);
                    uint128 amount = uint128((uint256(held) * bps) / 10_000);
                    if (amount == 0) amount = 1;
                    vm.prank(mole.ownerOf(id));
                    try mole.withdraw(id, amount) {
                        ++nWithdraw;
                        dustBudget += DUST_PER_LEG;
                    } catch {}
                }
                (rec0, rec1) = _valueAll();
            } else if (kind == 2) {
                uint256 id = _pickLive(_rnd(seed, step, 8));
                if (id != 0) {
                    (int24 lo, int24 hi) = _fuzzRange(_rnd(seed, step, 9), _rnd(seed, step, 10));
                    vm.prank(KEEPER);
                    try mole.rebalance(id, lo, hi) {
                        ++nRebalance;
                        dustBudget += 2 * DUST_PER_LEG; // burn leg + mint leg
                    } catch {
                        ++nRebalanceReverted;
                    }
                }
                (rec0, rec1) = _valueAll();
            } else {
                // Pure swap step. `rec0/rec1` from the end of the previous step is still a valid
                // "before" measurement: nothing but vm.warp has happened since.
                uint256 live = _liveCount();
                bool zeroForOne = _rnd(seed, step, 11) % 2 == 0;
                uint256 amt = bound(_rnd(seed, step, 12), 1e15, 2_000e18);

                uint128[] memory liqBefore = _snapshotStoredLiquidity();

                try this.externalSwap(zeroForOne, -int256(amt)) {
                    ++nSwap;
                } catch {}

                // A swap must not touch MolePositions state at all. If it did, the swap term below
                // could launder a real accounting move.
                _assertStoredLiquidityUnchanged(liqBefore);

                (uint256 n0, uint256 n1) = _valueAll();
                swapAtt0 += int256(n0) - int256(rec0);
                swapAtt1 += int256(n1) - int256(rec1);
                rec0 = n0;
                rec1 = n1;
                // Two valuations bracket this term (the previous step's and this one's).
                dustBudget += 2 * live * DUST_PER_VALUATION;
            }

            /* ---------------------------------------------- the invariant, every step */

            (int256 net0, int256 net1) = _userNet();
            uint256 allowed = dustBudget + _liveCount() * DUST_PER_VALUATION;

            int256 gap0 = int256(rec0) - (net0 + swapAtt0);
            int256 gap1 = int256(rec1) - (net1 + swapAtt1);

            if (_abs(gap0) > maxGap) maxGap = _abs(gap0);
            if (_abs(gap1) > maxGap) maxGap = _abs(gap1);

            if (_abs(gap0) > allowed || _abs(gap1) > allowed) {
                emit log_named_uint("step", step);
                emit log_named_uint("kind", kind);
                emit log_named_uint("recoverable0", rec0);
                emit log_named_uint("recoverable1", rec1);
                emit log_named_int("userNet0", net0);
                emit log_named_int("userNet1", net1);
                emit log_named_int("swapAttributed0", swapAtt0);
                emit log_named_int("swapAttributed1", swapAtt1);
                emit log_named_int("gap0", gap0);
                emit log_named_int("gap1", gap1);
                emit log_named_uint("allowed dust", allowed);
            }

            assertLe(_abs(gap0), allowed, "VALUE NOT CONSERVED in token0");
            assertLe(_abs(gap1), allowed, "VALUE NOT CONSERVED in token1");

            _assertNoInventory("stateful step");
        }

        // Non-vacuity: a trace that did nothing must not be able to pass.
        assertGe(nOpen, 2, "trace opened nothing");
        assertGe(nWithdraw + nRebalance + nSwap, 6, "trace exercised almost no actions");
        assertGe(nSwap, 1, "trace generated no fees");

        emit log_named_uint("opens", nOpen);
        emit log_named_uint("withdraws", nWithdraw);
        emit log_named_uint("rebalances", nRebalance);
        emit log_named_uint("rebalances reverted", nRebalanceReverted);
        emit log_named_uint("swaps", nSwap);
        emit log_named_uint("worst |gap| observed (wei)", maxGap);
        emit log_named_uint("dust budget at end of trace (wei)", dustBudget);
    }

    /* ------------------------------------------------------------------------------------------
       1b. NEGATIVE CONTROL — proof that the conservation check above can actually fail.

       A conservation test that has never been seen to trip is indistinguishable from
       `assertTrue(true)`. This reproduces the SHAPE of the 2026-08-01 bug — tokens leave the
       user side without ever appearing as recoverable position value — by moving them out of a
       user's wallet by hand, and asserts that the very same equality the stateful test uses
       breaks by exactly the leaked amount and by far more than the dust budget.
       ------------------------------------------------------------------------------------------ */
    function test_negativeControl_theConservationCheckDetectsALeak() public {
        uint256 id = _openAs(ALICE, -600, 600, 100e18);
        ids.push(id);

        (uint256 rec0,) = _valueAll();
        (int256 net0,) = _userNet();
        uint256 clean = _abs(int256(rec0) - net0);
        assertLe(clean, DUST_PER_LEG + DUST_PER_VALUATION, "the clean trace is not clean");

        // The leak: 1e12 wei of a user's token0 goes somewhere that is not a Mole position. This is
        // structurally what `_settleNet` did, except it parked it in address(this) instead.
        uint256 LEAK = 1e12;
        vm.prank(ALICE);
        tok0.transfer(address(0xBAD), LEAK);

        (uint256 rec0b,) = _valueAll();
        (int256 net0b,) = _userNet();
        uint256 dirty = _abs(int256(rec0b) - net0b);

        assertGt(dirty, DUST_PER_LEG + DUST_PER_VALUATION, "THE CONSERVATION CHECK IS BLIND TO A LEAK");
        assertApproxEqAbs(dirty, LEAK, DUST_PER_LEG + DUST_PER_VALUATION, "the check mis-sizes the leak");
        emit log_named_uint("gap with no leak (wei)", clean);
        emit log_named_uint("gap after a 1e12 wei leak", dirty);
    }

    /// @dev A range anchored on the CURRENT tick. The offset is signed and the width is wide, so
    ///      the corpus contains straddling ranges (both tokens live), ranges entirely above the
    ///      price and ranges entirely below it, without ever producing an invalid tick.
    function _fuzzRange(uint256 rA, uint256 rB) internal view returns (int24 lo, int24 hi) {
        int24 cur = _alignedTick();
        int24 off = int24(bound(int256(rA % 256), -120, 40)) * SPACING; // -7200 .. +2400
        int24 width = int24(bound(int256(rB % 256), 1, 180)) * SPACING; // 60 .. 10800
        lo = cur + off;
        hi = lo + width;
        // Keep well inside usable tick space; the pool never travels anywhere near these.
        if (lo < -600_000) lo = -600_000;
        if (hi > 600_000) hi = 600_000;
        if (hi - lo < MIN_WIDTH) hi = lo + MIN_WIDTH;
    }

    function _pickLive(uint256 r) internal view returns (uint256) {
        uint256 n = ids.length;
        if (n == 0) return 0;
        for (uint256 i; i < n; ++i) {
            uint256 id = ids[(r + i) % n];
            if (mole.getPosition(id).liquidity != 0) return id;
        }
        return 0;
    }

    function _snapshotStoredLiquidity() internal view returns (uint128[] memory out) {
        out = new uint128[](ids.length);
        for (uint256 i; i < ids.length; ++i) {
            out[i] = mole.getPosition(ids[i]).liquidity;
        }
    }

    function _assertStoredLiquidityUnchanged(uint128[] memory before) internal view {
        for (uint256 i; i < before.length; ++i) {
            assertEq(mole.getPosition(ids[i]).liquidity, before[i], "a swap mutated a Mole position");
        }
    }

    /* ==========================================================================================
       2.  REBALANCE VALUE CONSERVATION — the exact property whose absence was the exploit
       ========================================================================================== */

    /// @notice For random (startRange, endRange, liquidity, price): the token value of a position
    ///         immediately BEFORE a rebalance equals its value immediately AFTER, plus whatever
    ///         dust the rebalance paid to the owner in the same transaction.
    ///
    ///             value_before  ==  value_after + dustToOwner        (± ROUND_TRIP_DUST)
    ///
    ///         A rebalance moves no price, so both valuations are taken at the same price and are
    ///         directly comparable. This is the identity `rebalance()` broke: holding the LIQUIDITY
    ///         NUMBER constant while moving the range makes value_after a function of range width,
    ///         and the difference went to address(this) with no owner leg.
    ///
    /// DUST DERIVATION for this test, exactly: let e be the truncation of a valuation exit (0..1
    ///         wei/token), b the truncation of the rebalance's burn leg (0..1), and c the round-up
    ///         of its mint leg (0..1). Then
    ///             value_before − value_after − dust  =  b + e_after − e_before + c  ∈ [−1, +3].
    ///         ROUND_TRIP_DUST = 4 is a strict cap on |that|, not a fitted constant.
    ///
    /// forge-config: default.fuzz.runs = 1024
    /// forge-config: deep.fuzz.runs = 50000
    function testFuzz_rebalanceConservesTokenValue(
        uint256 liqRaw,
        uint256 startOff,
        uint256 startWidth,
        uint256 endOff,
        uint256 endWidth,
        uint256 priceKick
    ) public {
        _rebalanceConservationCase(liqRaw, startOff, startWidth, endOff, endWidth, priceKick);
    }

    /// @notice Proof that the corpus above is not vacuous. Fuzz state resets between runs, so a
    ///         counter inside the fuzz test could never be read; this replays 160 pseudo-random
    ///         draws through the IDENTICAL case body in a single run and asserts on the outcome
    ///         mix. If a change ever made 90% of draws bounce off a revert, this trips even though
    ///         the fuzz test would still be green.
    function test_rebalanceCorpusIsNotVacuous() public {
        uint256 refusedOpen;
        uint256 refusedRebalance;
        uint256 executed;

        for (uint256 i; i < 160; ++i) {
            uint8 outcome = _rebalanceConservationCase(
                _rnd(0xC0FFEE, i, 0),
                _rnd(0xC0FFEE, i, 1),
                _rnd(0xC0FFEE, i, 2),
                _rnd(0xC0FFEE, i, 3),
                _rnd(0xC0FFEE, i, 4),
                _rnd(0xC0FFEE, i, 5)
            );
            if (outcome == 0) ++refusedOpen;
            else if (outcome == 1) ++refusedRebalance;
            else ++executed;
        }

        emit log_named_uint("cases: open refused", refusedOpen);
        emit log_named_uint("cases: rebalance refused", refusedRebalance);
        emit log_named_uint("cases: rebalance EXECUTED and value-checked", executed);

        // The value-conservation assertions only run on the `executed` branch, so that branch is
        // the whole test. A majority of draws must reach it.
        // Measured at the time of writing: 97 executed / 63 refused / 0 open-refused out of 160.
        // The refusals are legitimate — a range on the far side of the price from the burned tokens
        // cannot be funded without swapping, and the contract correctly refuses rather than trading
        // on the owner's behalf. The floor is set at half so this guard survives a corpus tweak
        // while still failing loudly if the property branch stops being reached.
        assertGe(executed, 80, "REBALANCE CORPUS IS VACUOUS: fewer than half of draws rebalanced");
        // ...and the refusal paths must be exercised too, or their assertions are dead code.
        assertGt(refusedRebalance, 0, "no draw exercised the refused-rebalance path");
    }

    /// @return outcome 0 = open refused, 1 = rebalance refused, 2 = rebalance executed and checked.
    function _rebalanceConservationCase(
        uint256 liqRaw,
        uint256 startOff,
        uint256 startWidth,
        uint256 endOff,
        uint256 endWidth,
        uint256 priceKick
    ) internal returns (uint8 outcome) {
        // ---- random price: push the pool somewhere with a real swap before anything is opened.
        //      Direction and size both come from the draw, so the corpus covers the whole tick
        //      band a 20,000e18 book can be pushed across (~ -9,500 .. +9,500).
        {
            bool z4o = priceKick % 2 == 0;
            uint256 amt = bound(priceKick, 1e15, 3_000e18);
            try this.externalSwap(z4o, -int256(amt)) {} catch {}
        }

        (int24 lo0, int24 hi0) = _fuzzRange(startOff, startWidth);
        uint128 liq = uint128(bound(liqRaw, 1e9, 1e22));

        uint256 countBefore = mole.positionCount();
        vm.prank(ALICE);
        uint256 id;
        try mole.open(key, lo0, hi0, liq, type(uint256).max, type(uint256).max, block.timestamp)
        returns (uint256 _id) {
            id = _id;
        } catch {
            // An open that cannot be funded or exceeds the per-tick cap must leave nothing behind.
            assertEq(mole.positionCount(), countBefore, "a reverted open created a position");
            _assertNoInventory("after a reverted open");
            return 0;
        }
        ids.push(id);

        (uint256 before0, uint256 before1) = _valueOne(id);
        _assertNoInventory("before rebalance");

        (int24 lo1, int24 hi1) = _fuzzRange(endOff, endWidth);
        vm.warp(block.timestamp + MIN_REBAL_INTERVAL);

        (uint256 w0, uint256 w1) = _bal(ALICE);
        vm.prank(KEEPER);
        try mole.rebalance(id, lo1, hi1) {
            // fallthrough
        } catch {
            // A rebalance can legitimately be impossible: if the price sits outside both ranges on
            // opposite sides, the burn returns only token0 and the new range needs only token1, so
            // getLiquidityForAmounts is 0 and the contract refuses rather than swapping on the
            // owner's behalf. What must NOT happen is that it half-executes.
            MolePositions.Position memory pr = mole.getPosition(id);
            assertEq(pr.tickLower, lo0, "reverted rebalance moved the range");
            assertEq(pr.tickUpper, hi0, "reverted rebalance moved the range");
            assertEq(pr.liquidity, liq, "reverted rebalance moved liquidity");
            (uint256 same0, uint256 same1) = _valueOne(id);
            assertEq(same0, before0, "reverted rebalance changed token0 value");
            assertEq(same1, before1, "reverted rebalance changed token1 value");
            _assertNoInventory("after a reverted rebalance");
            return 1;
        }

        (uint256 x0, uint256 x1) = _bal(ALICE);
        uint256 dust0 = x0 - w0;
        uint256 dust1 = x1 - w1;

        (uint256 after0, uint256 after1) = _valueOne(id);

        // The contract is not allowed to be the place any of this value went.
        _assertNoInventory("after rebalance");

        // No value created: a rebalance cannot mint tokens out of nothing.
        assertLe(after0 + dust0, before0 + ROUND_TRIP_DUST, "REBALANCE CREATED token0 VALUE");
        assertLe(after1 + dust1, before1 + ROUND_TRIP_DUST, "REBALANCE CREATED token1 VALUE");

        // No value destroyed/diverted: this is the exploit's exact signature.
        assertGe(after0 + dust0 + ROUND_TRIP_DUST, before0, "REBALANCE LOST token0 VALUE");
        assertGe(after1 + dust1 + ROUND_TRIP_DUST, before1, "REBALANCE LOST token1 VALUE");

        // And the range really did move to where the keeper asked.
        MolePositions.Position memory p = mole.getPosition(id);
        assertEq(p.tickLower, lo1, "range not applied");
        assertEq(p.tickUpper, hi1, "range not applied");
        assertEq(p.liquidity, _onChainLiquidity(id, lo1, hi1), "stored liquidity != PoolManager");
        if (lo0 != lo1 || hi0 != hi1) {
            assertEq(_onChainLiquidity(id, lo0, hi0), 0, "old range not emptied");
        }
        return 2;
    }

    /* ==========================================================================================
       3.  FEES COMPOUND, THEY DO NOT LEAK
       ========================================================================================== */

    /// @notice Generate real fees by swapping, then rebalance to the IDENTICAL range. Post-fix the
    ///         accrued fees come back on the burn leg and are re-minted into the owner's own
    ///         position, so:
    ///           - `p.liquidity` must STRICTLY INCREASE (a same-range rebalance is a compounding
    ///             operation, not a no-op and definitely not a tax), and
    ///           - the contract's balance must still be exactly zero.
    ///         Pre-fix this same call was a pure fee-theft primitive: callerDelta on the burn leg
    ///         carries principal + fees, and the whole fee component was taken to address(this).
    function test_feesCompoundIntoTheOwnerPositionRatherThanLeaking() public {
        uint128 liq = 500e18;
        uint256 id = _openAs(ALICE, -600, 600, liq);
        // Byte-identical control that is never rebalanced.
        uint256 controlId = _openAs(BOB, -600, 600, liq);

        (uint256 valueBefore0, uint256 valueBefore1) = _valueOne(id);

        _churnFees(50e18, 8);
        _assertNoInventory("after fee churn");

        (uint256 feed0, uint256 feed1) = _valueOne(id);
        // Sanity: the swaps really did pay this position something.
        assertGt(feed0 + feed1, valueBefore0 + valueBefore1, "the churn generated no fee income");

        (uint256 ab0, uint256 ab1) = _bal(ALICE);

        vm.warp(block.timestamp + MIN_REBAL_INTERVAL);
        vm.prank(KEEPER);
        mole.rebalance(id, -600, 600); // SAME range in, SAME range out

        // (1) liquidity strictly increased — the fees became principal.
        uint128 newLiq = mole.getPosition(id).liquidity;
        assertGt(newLiq, liq, "FEES DID NOT COMPOUND: same-range rebalance did not raise liquidity");
        assertEq(newLiq, _onChainLiquidity(id, -600, 600), "stored liquidity != PoolManager");

        // (2) the contract balance stayed exactly zero.
        _assertNoInventory("after the same-range rebalance");

        // (3) nothing leaked: value after (position + the dust that could not be re-minted) equals
        //     value before the rebalance, to within one burn+mint round trip.
        (uint256 aa0, uint256 aa1) = _bal(ALICE);
        (uint256 after0, uint256 after1) = _valueOne(id);
        assertGe(after0 + (aa0 - ab0) + ROUND_TRIP_DUST, feed0, "token0 leaked out of the rebalance");
        assertGe(after1 + (aa1 - ab1) + ROUND_TRIP_DUST, feed1, "token1 leaked out of the rebalance");

        // (4) and the rebalanced LP is not behind the untouched control.
        (uint256 c0, uint256 c1) = _valueOne(controlId);
        assertGe(after0 + (aa0 - ab0) + ROUND_TRIP_DUST, c0, "rebalanced LP was taxed vs control (token0)");
        assertGe(after1 + (aa1 - ab1) + ROUND_TRIP_DUST, c1, "rebalanced LP was taxed vs control (token1)");

        // Real exits, so the compounded liquidity is provably spendable and not just a number.
        vm.prank(ALICE);
        mole.withdraw(id, newLiq);
        vm.prank(BOB);
        mole.withdraw(controlId, liq);
        _assertNoInventory("after both exits");
    }

    /* ==========================================================================================
       4.  ROUNDING DIRECTION — no free money, at any magnitude
       ========================================================================================== */

    /// @notice Over an open -> partial withdraw -> withdraw-the-rest round trip at a fixed price,
    ///         the user must NEVER receive more of either token than they paid in. v4 rounds the
    ///         mint charge up and the burn payout down, so the only correct direction is a loss of
    ///         a few wei; anything else is a mint-from-nothing primitive that can be farmed.
    ///
    ///         Liquidity is drawn LOG-UNIFORMLY over the entire uint128 range: `expBits` picks a
    ///         binade and the mantissa fills it, so 1 wei, 2**64 and 2**128-1 are all reachable
    ///         with equal probability rather than the ~0 probability a uniform draw would give the
    ///         small end. Draws that v4 refuses (per-tick liquidity cap, int128 overflow) are
    ///         asserted to leave NOTHING behind rather than being skipped.
    ///
    /// forge-config: default.fuzz.runs = 1024
    /// forge-config: deep.fuzz.runs = 50000
    function testFuzz_openWithdrawRoundTripNeverPaysOutMoreThanItTookIn(
        uint256 expRaw,
        uint256 mantRaw,
        uint256 offRaw,
        uint256 widthRaw,
        uint256 fracRaw
    ) public {
        _roundTripCase(expRaw, mantRaw, offRaw, widthRaw, fracRaw);
    }

    /// @notice Non-vacuity proof for the round-trip corpus, same reasoning as
    ///         `test_rebalanceCorpusIsNotVacuous`: 200 pseudo-random draws through the identical
    ///         body in one run, asserting that the branch carrying the rounding assertions is the
    ///         one most draws land on, AND that draws which actually move a non-zero amount of
    ///         BOTH tokens are common (a corpus of 1-wei positions would satisfy `got <= paid`
    ///         with 0 <= 0 forever and prove nothing).
    function test_roundTripCorpusIsNotVacuous() public {
        uint256 refused;
        uint256 completed;
        uint256 movedBothTokens;

        for (uint256 i; i < 200; ++i) {
            (bool ok, bool bothTokens) = _roundTripCase(
                _rnd(0xBEEF, i, 0), _rnd(0xBEEF, i, 1), _rnd(0xBEEF, i, 2), _rnd(0xBEEF, i, 3), _rnd(0xBEEF, i, 4)
            );
            if (ok) {
                ++completed;
                if (bothTokens) ++movedBothTokens;
            } else {
                ++refused;
            }
        }

        emit log_named_uint("round trips completed", completed);
        emit log_named_uint("round trips refused (cap/overflow)", refused);
        emit log_named_uint("round trips that moved BOTH tokens", movedBothTokens);

        assertGe(completed, 120, "ROUND-TRIP CORPUS IS VACUOUS: most draws never opened");
        assertGe(movedBothTokens, 40, "ROUND-TRIP CORPUS IS DEGENERATE: too few two-sided positions");
        assertGt(refused, 0, "no draw reached the uint128 / per-tick ceiling");
    }

    /// @return ok        true if the open was accepted and the round trip actually ran.
    /// @return bothSided true if the position really charged non-zero amounts of BOTH tokens.
    function _roundTripCase(
        uint256 expRaw,
        uint256 mantRaw,
        uint256 offRaw,
        uint256 widthRaw,
        uint256 fracRaw
    ) internal returns (bool ok, bool bothSided) {
        uint256 e = bound(expRaw, 0, 127);
        uint256 span = uint256(1) << e;
        uint128 liq = uint128(bound(mantRaw, span, (span << 1) - 1));

        (int24 lo, int24 hi) = _fuzzRange(offRaw, widthRaw);

        (uint256 s0, uint256 s1) = _bal(ALICE);

        uint256 countBefore = mole.positionCount();
        vm.prank(ALICE);
        uint256 id;
        try mole.open(key, lo, hi, liq, type(uint256).max, type(uint256).max, block.timestamp)
        returns (uint256 _id) {
            id = _id;
        } catch {
            // A refused open must be a complete no-op: no position, no charge, no inventory.
            assertEq(mole.positionCount(), countBefore, "a refused open still created a position");
            (uint256 u0, uint256 u1) = _bal(ALICE);
            assertEq(u0, s0, "a refused open still charged token0");
            assertEq(u1, s1, "a refused open still charged token1");
            _assertNoInventory("after a refused open");
            return (false, false);
        }

        (uint256 o0, uint256 o1) = _bal(ALICE);
        uint256 paid0 = s0 - o0;
        uint256 paid1 = s1 - o1;

        uint256 bps = bound(fracRaw, 1, 10_000);
        uint128 part = uint128((uint256(liq) * bps) / 10_000);
        if (part == 0) part = 1;
        if (part > liq) part = liq;

        vm.prank(ALICE);
        mole.withdraw(id, part);
        if (part < liq) {
            vm.prank(ALICE);
            mole.withdraw(id, liq - part);
        }

        assertEq(mole.getPosition(id).liquidity, 0, "position not fully closed");

        (uint256 e0, uint256 e1) = _bal(ALICE);
        uint256 got0 = e0 - o0;
        uint256 got1 = e1 - o1;

        // THE ROUNDING DIRECTION. No fees were earned (no swaps), the price never moved, so a
        // correct implementation can only ever return LESS than it took.
        assertLe(got0, paid0, "FREE MONEY: round trip returned more token0 than it collected");
        assertLe(got1, paid1, "FREE MONEY: round trip returned more token1 than it collected");

        // ...and the loss is bounded dust, so this is not passing by simply eating the deposit.
        assertGe(got0 + ROUND_TRIP_DUST, paid0, "round trip lost more token0 than rounding dust");
        assertGe(got1 + ROUND_TRIP_DUST, paid1, "round trip lost more token1 than rounding dust");

        _assertNoInventory("after the round trip");
        return (true, paid0 > 0 && paid1 > 0);
    }

    /// @notice The named magnitudes, pinned deterministically so they are covered on every run of
    ///         the suite and not merely reachable by the fuzzer: 1 wei, 2**32, 2**64, 2**96, and
    ///         the top of the uint128 range.
    function test_roundTripRoundingAtTheNamedMagnitudes() public {
        uint128[7] memory mags = [
            uint128(1),
            uint128(2),
            uint128(1) << 32,
            uint128(1) << 64,
            uint128(1) << 96,
            uint128(1) << 126,
            type(uint128).max
        ];

        uint256 accepted;
        uint256 refused;

        for (uint256 i; i < mags.length; ++i) {
            (uint256 s0, uint256 s1) = _bal(ALICE);
            vm.prank(ALICE);
            uint256 id;
            try mole.open(key, -600, 600, mags[i], type(uint256).max, type(uint256).max, block.timestamp)
            returns (uint256 _id) {
                id = _id;
                ++accepted;
            } catch {
                ++refused;
                (uint256 u0, uint256 u1) = _bal(ALICE);
                assertEq(u0, s0, "refused open charged token0");
                assertEq(u1, s1, "refused open charged token1");
                _assertNoInventory("after refused open");
                continue;
            }

            (uint256 o0, uint256 o1) = _bal(ALICE);
            vm.prank(ALICE);
            mole.withdraw(id, mags[i]);
            (uint256 x0, uint256 x1) = _bal(ALICE);

            assertLe(x0 - o0, s0 - o0, string.concat("FREE MONEY token0 at magnitude index ", vm.toString(i)));
            assertLe(x1 - o1, s1 - o1, string.concat("FREE MONEY token1 at magnitude index ", vm.toString(i)));
            assertGe(x0 - o0 + ROUND_TRIP_DUST, s0 - o0, "lost more than dust in token0");
            assertGe(x1 - o1 + ROUND_TRIP_DUST, s1 - o1, "lost more than dust in token1");
            _assertNoInventory("after magnitude round trip");
        }

        // Both ends of the range must actually be exercised, or this test proves nothing.
        assertGt(accepted, 0, "no magnitude was accepted");
        assertGt(refused, 0, "no magnitude hit the uint128/per-tick ceiling");
        emit log_named_uint("magnitudes accepted", accepted);
        emit log_named_uint("magnitudes refused (cap/overflow)", refused);
    }

    /* ==========================================================================================
       5.  MULTI-USER ISOLATION AT AN IDENTICAL TICK RANGE
       ========================================================================================== */

    /// @notice Two users open at the byte-identical tick range in the same pool; one exits fully.
    ///         The other must be untouched in all three observable senses: recorded liquidity,
    ///         PoolManager liquidity at its own salt, and recoverable tokens — the last to the wei,
    ///         with no dust tolerance at all, because a neighbour's burn writes nothing that a
    ///         separate position slot can read.
    ///
    /// forge-config: default.fuzz.runs = 1024
    /// forge-config: deep.fuzz.runs = 50000
    function testFuzz_identicalRangeNeighbourIsUnaffectedByAFullExit(
        uint256 victimLiqRaw,
        uint256 exiterLiqRaw,
        uint256 offRaw,
        uint256 widthRaw,
        uint256 churnRaw,
        bool victimFirst
    ) public {
        (int24 lo, int24 hi) = _fuzzRange(offRaw, widthRaw);
        uint128 victimLiq = uint128(bound(victimLiqRaw, 1e9, 1e22));
        uint128 exiterLiq = uint128(bound(exiterLiqRaw, 1e9, 1e22));

        uint256 victimId;
        uint256 exiterId;
        if (victimFirst) {
            victimId = _openAs(ALICE, lo, hi, victimLiq);
            exiterId = _openAs(BOB, lo, hi, exiterLiq);
        } else {
            exiterId = _openAs(BOB, lo, hi, exiterLiq);
            victimId = _openAs(ALICE, lo, hi, victimLiq);
        }
        assertTrue(victimId != exiterId, "ids must be distinct");

        // Real fee income in the shared range, so the two positions have live fee-growth state and
        // the isolation claim is not tested on a frozen pool.
        _churnFees(bound(churnRaw, 1e15, 200e18), 3);

        uint128 recordedBefore = mole.getPosition(victimId).liquidity;
        uint128 onChainBefore = _onChainLiquidity(victimId, lo, hi);
        (uint256 v0, uint256 v1) = _valueOne(victimId);
        assertEq(recordedBefore, victimLiq, "victim liquidity changed before anything happened");
        assertEq(onChainBefore, victimLiq, "victim pool liquidity != recorded");

        // The neighbour exits everything, then tries to take one wei more.
        vm.prank(BOB);
        mole.withdraw(exiterId, exiterLiq);
        vm.prank(BOB);
        vm.expectRevert(MolePositions.InsufficientLiquidity.selector);
        mole.withdraw(exiterId, 1);

        // (1) recorded liquidity
        assertEq(mole.getPosition(victimId).liquidity, recordedBefore, "neighbour's exit changed recorded liquidity");
        // (2) actual PoolManager liquidity at the victim's own salt
        assertEq(_onChainLiquidity(victimId, lo, hi), onChainBefore, "neighbour's exit changed pool liquidity");
        // (3) recoverable tokens — exactly, no tolerance
        (uint256 v0b, uint256 v1b) = _valueOne(victimId);
        assertEq(v0b, v0, "neighbour's exit changed the victim's recoverable token0");
        assertEq(v1b, v1, "neighbour's exit changed the victim's recoverable token1");

        // And the victim can actually get it out.
        (uint256 a0, uint256 a1) = _bal(ALICE);
        vm.prank(ALICE);
        mole.withdraw(victimId, recordedBefore);
        (uint256 b0, uint256 b1) = _bal(ALICE);
        assertEq(b0 - a0, v0b, "victim's real payout != its measured recoverable token0");
        assertEq(b1 - a1, v1b, "victim's real payout != its measured recoverable token1");
        assertEq(mole.getPosition(victimId).liquidity, 0, "victim not closed");
        _assertNoInventory("after both users exit");
    }

    /* ------------------------------------------------------------------- shared */

    function _openAs(address who, int24 lo, int24 hi, uint128 liq) internal returns (uint256 id) {
        vm.prank(who);
        id = mole.open(key, lo, hi, liq, type(uint256).max, type(uint256).max, block.timestamp);
    }
}
